import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import sabyasachi from "../public/dev-ed-wave.png";
import { useState } from 'react';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);


  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title className="">Sabyasachi Sarkar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl dark:text-white text-black">
              Sabyasachi Sarkar
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => {
                    setDarkMode(!darkMode);
                    console.log("clicked");
                  }}
                  className=" cursor-pointer text-2xl dark:text-white text-black"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href=" https://drive.google.com/file/d/1IQbwDu-ycQHrvJ1gVAvk7BxLVJCrW3Ud/view?usp=sharing"
                  target="_blank"
                  rel="noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Sabyasachi Sarkar
            </h2>
            <h3 className="text-2xl py-2 dark:text-white text-black md:text-3xl">
              Developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below and let&apos;s get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="https://github.com/sabyasachi4943"
                target="_blank"
                rel="noreferrer"
              >
                <AiFillGithub />
              </a>
              <a
                href="https://twitter.com/sabyasachiCodes"
                target="_blank"
                rel="noreferrer"
              >
                <AiFillTwitterCircle />
              </a>
              <a
                href="https://www.linkedin.com/in/sabyasachisarkar001"
                target="_blank"
                rel="noreferrer"
              >
                <AiFillLinkedin />
              </a>
            </div>
            <div className="mx-auto flex items-center justify-center  bg-gradient-to-b from-teal-500 rounded-full lg:w-80 lg:h-80 w-40 h-40 relative overflow-hidden mt-20 md:h-80 md:w-80">
              <Image src={sabyasachi} layout="fill" objectFit="cover" alt="" />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
